### ISSUE TITLE
Wrong gameDir

### ISSUE THREAD

**Issue by Curly-** [Curly-/Mod-pack#11]
In launcher_profiles.json, the "gameDir" value is set to "...\\.minecraft" even though the install directory is different.

**Comment by Curly-** [comment]
Reinstalled. Worked this time.

**Comment by Curly-** [comment]
However, something that isn't correct in that file, is the "lastVersionId" variable. It defaults to "0.0-Forge0.0"

**Comment by TheArni** [comment]
This issue was moved to TheArni/ModpackInstaller#6
